/**
* ATC_loadoutParamsA
* ["atc_unitSpecClasses", array Unit classes, false];
    [
        string Unit class,
        [
            array 0 List of allowed weapon,
            array 1 List of allowed optics,
            array 2 List of allowed pointers,
            array 3 List of allowed muzzle items,
            array 4 List of additional ammo (ex: explosives),
            array 5 List of restricted ammo,
            array 6 List of allowed items (ex: )
        ]
    ]
*/
[
    [
        "Common",
        [
            ["hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_P07_F","arifle_MX_F","arifle_MXC_F","SMG_02_F","ATC_TITAN_AA_starter"],
            ["optic_Holosight","optic_aco","optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            ["acc_pointer_IR","ACE_acc_pointer_red","acc_flashlight"],
            [],
            ["ACE_HandFlare_White","ACE_Chemlight_HiWhite","HandGrenade","SmokeShellBlue","SmokeShellGreen","SmokeShellOrange","SmokeShellPurple","SmokeShellRed","SmokeShellYellow","SmokeShell","B_IR_Grenade","Chemlight_blue","Chemlight_green","Chemlight_red","Chemlight_yellow","ClaymoreDirectionalMine_Remote_Mag","SatchelCharge_Remote_Mag","DemoCharge_Remote_Mag","ATMine_Range_Mag","APERSMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["V_TacChestrig_grn_F","H_Booniehat_khk_hs","ACE_MapTools","ACE_wirecutter","ACE_EarPlugs","ACE_Flashlight_MX991","ACE_IR_Strobe_Item","ItemMap","ItemCompass","ItemWatch","tf_anprc152","FirstAidKit","NVGoggles","Binocular"]
        ]
    ],
    [
        "Commander",
        [
            [],
            ["ACE_optic_Hamr_PIP"],
            [],
            [],
            [],
            [],
            ["H_Beret_Colonel","H_HelmetB_snakeskin","B_UavTerminal","ACE_DAGR","ACE_microDAGR","ACE_Vector","ACE_Kestrel4500","ACE_DAGR"]
        ]
    ],
    [
        "Logistic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["ACE_DAGR","ACE_NVG_Wide"]
        ]
    ],
    [
        "Medic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["Medikit"]
        ]
    ],
	[
        "TL",
        [
            ["arifle_MX_GL_F"],
            ["ACE_optic_Hamr_PIP"],
            [],
            [],
            ["ACE_HuntIR_M203","1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"],
            [],
            ["ACE_HuntIR_monitor","ACE_microDAGR"]
        ]
    ],
    [
        "Grenadier",
        [
            ["arifle_MX_GL_F"],
            [],
            [],
            [],
            ["ACE_HuntIR_M203","1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"],
            [],
            ["ACE_HuntIR_monitor"]
        ]
    ],
    [
        "LMG",
        [
            ["arifle_MX_SW_F","LMG_03_F"],
            [],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp"],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "HMG",
        [
            ["LMG_Mk200_F","MMG_02_sand_F","LMG_03_F","arifle_MX_SW_F"],
            [],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp"],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "SpecialForces",
        [
            ["srifle_DMR_03_khaki_F","arifle_MXM_F","arifle_MX_Black_F","arifle_MX_SW_Black_F","arifle_SPAR_01_GL_blk_F","arifle_SPAR_01_blk_F","tf47_m3maaws","arifle_MXC_Black_F","arifle_SDAR_F","hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_P07_F","SMG_02_F","SMG_05_F","LMG_03_F"],
            ["tf47_optic_m3maaws","ACE_optic_MRCO_PIP","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP","optic_Holosight","optic_aco","optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp","acc_pointer_IR","ACE_acc_pointer_red"],
            ["muzzle_snds_M","muzzle_snds_L","muzzle_snds_H","muzzle_snds_acp","muzzle_snds_65_TI_blk_F"],
            ["ClaymoreDirectionalMine_Remote_Mag","Laserbatteries","DemoCharge_Remote_Mag","ATMine_Range_Mag","APERSMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag","SatchelCharge_Remote_Mag"],
            [],
            ["ACE_Flashlight_MX991","V_TacChestrig_grn_F","H_Booniehat_khk_hs","ACE_Clacker","ACE_SpottingScopeObject","ACE_SpottingScope","ACE_Altimeter","ACE_DAGR","ACE_microDAGR","ACE_NVG_Gen4","ACE_NVG_Wide","ATC_Laserdesignator_B"]
        ]   
    ],
    [
        "EXP",//obsolete
        [
            [],
            [],
            [],
            [],
            ["ClaymoreDirectionalMine_Remote_Mag","SatchelCharge_Remote_Mag","DemoCharge_Remote_Mag","ATMine_Range_Mag","APERSMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["ACE_M26_Clacker","ACE_DefusalKit"]
        ]   
    ],
    [
        "ENG",
        [
            ["ACE_VMM3"],
            [],
            [],
            [],
            [],
            [],
            ["ToolKit"]
        ]
    ],
    [
        "AT",
        [
            ["tf47_m3maaws"],
            ["tf47_optic_m3maaws"],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAT",
        [
            ["ATC_TITAN_AT_B"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAA",
        [
            ["ATC_TITAN_AA_B"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "Sniper",
        [
            ["arifle_MXM_F","srifle_LRR_camo_F","srifle_DMR_02_camo_F","srifle_EBR_F","srifle_DMR_03_khaki_F"],
            ["ACE_optic_SOS_PIP","ACE_optic_LRPS_PIP","optic_AMS_snd","optic_AMS_snd","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP","optic_NVS"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp"],
            ["muzzle_snds_L","muzzle_snds_acp","muzzle_snds_338_sand","muzzle_snds_B_snd_F"],
            [],
            [],
            ["U_B_GhillieSuit","ACE_Altimeter","ACE_Tripod","ACE_RangeCard"]
        ]   
    ],
    [
        "Spotter",
        [
            ["arifle_MX_GL_F","arifle_MXM_F","arifle_SPAR_01_GL_blk_F","arifle_SPAR_01_blk_F"],
            ["ACE_optic_SOS_PIP","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp"],
            ["muzzle_snds_L","muzzle_snds_acp"],
            ["APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag","Laserbatteries"],
            [],
            ["U_B_GhillieSuit","ACE_SpottingScopeObject","ACE_Altimeter","ACE_SpottingScope","ACE_RangeCard","ACE_ATragMX","ACE_Kestrel4500","ACE_DAGR","ACE_microDAGR","ACE_Vector","ATC_Laserdesignator_B"]
        ]   
    ],
	[
        "Marksman",
        [
            ["arifle_MXM_F"],
            ["ACE_optic_SOS_PIP","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp"],
            [],
            [],
            [],
            ["ACE_RangeCard"]
        ]   
    ],
	    [
        "Mortarist",
        [
            [],
            [],
            [],
            [],
            ["ACE_1Rnd_82mm_Mo_HE","ACE_1Rnd_82mm_Mo_Smoke","ACE_1Rnd_82mm_Mo_Illum","ACE_1Rnd_82mm_Mo_HE_LaserGuided"],
            [],
            ["ACE_RangeTable_82mm","ACE_Kestrel4500","ACE_DAGR"]
        ]
    ],
    [
        "DM",
        [
            ["arifle_MXM_F","srifle_EBR_F","srifle_DMR_03_khaki_F"],
            ["optic_AMS_snd","ACE_optic_SOS_PIP","ACE_optic_LRPS_PIP","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP","ACE_optic_Hamr_PIP","optic_NVS"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp"],
            [],
            [],
            [],
            ["ACE_RangeCard","ACE_Kestrel4500"]
        ]   
    ]
]
