/**
* ATC_loadoutParamsA
* ["atc_unitSpecClasses", array Unit classes, false];
    [
        string Unit class,
        [
            array 0 List of allowed weapon,
            array 1 List of allowed optics,
            array 2 List of allowed pointers,
            array 3 List of allowed muzzle items,
            array 4 List of additional ammo (ex: explosives),
            array 5 List of restricted ammo,
            array 6 List of allowed items (ex: )
        ]
    ]
*/
[
    [
        "Common",
        [
            ["hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_Rook40_F","SMG_01_F","arifle_Katiba_F","arifle_Katiba_C_F","ATC_TITAN_AA_starter"],
            ["optic_ACO_grn","optic_Holosight","optic_aco","optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            ["acc_pointer_IR","ACE_acc_pointer_red","acc_flashlight"],
            [],
            ["HandGrenade","SmokeShellBlue","SmokeShellGreen","SmokeShellOrange","SmokeShellPurple","SmokeShellRed","SmokeShell","SmokeShellYellow","O_IR_Grenade","Chemlight_blue","Chemlight_green","Chemlight_red","Chemlight_yellow","ClaymoreDirectionalMine_Remote_Mag","SatchelCharge_Remote_Mag","DemoCharge_Remote_Mag","ATMine_Range_Mag","APERSBoundingMine_Range_Mag","APERSTripMine_Wire_Mag","APERSMine_Range_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["H_HelmetO_ocamo","U_O_CombatUniform_ocamo","V_I_G_resistanceLeader_F","ACE_Flashlight_MX991","V_HarnessO_brn","H_MilCap_ocamo","ACE_MapTools","ACE_wirecutter","ACE_EarPlugs","ACE_Flashlight","ACE_IR_Strobe_Item","ItemMap","ItemCompass","ItemWatch","tf_fadak","FirstAidKit","NVGoggles_OPFOR","Binocular"]
        ]
    ],
    [
        "Commander",
        [
            ["arifle_CTARS_blk_F"],
            ["ACE_optic_Arco_PIP"],
            [],
            [],
            [],
            [],
            ["U_O_OfficerUniform_ocamo","H_Beret_blk","H_HelmetO_ocamo","O_UavTerminal","ACE_DAGR","ACE_microDAGR","ACE_Vector","ACE_Kestrel4500","ACE_DAGR"]
        ]
    ],
	[
        "TL",
        [
            ["arifle_Katiba_GL_F"],
            ["ACE_optic_Arco_PIP"],
            [],
            [],
            ["ACE_HuntIR_M203","1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"],
            [],
            ["ACE_microDAGR","ACE_HuntIR_monitor"]
        ]
    ],
    [
        "Logistic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["ACE_DAGR","ACE_NVG_Wide"]
        ]
    ],
    [
        "Medic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["Medikit"]
        ]
    ],
    [
        "Grenadier",
        [
            ["arifle_Katiba_GL_F"],
            [],
            [],
            [],
            ["ACE_HuntIR_M203","1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"],
            [],
            ["ACE_HuntIR_monitor"]
        ]
    ],
    [
        "LMG",
        [
            ["arifle_CTARS_blk_F","LMG_Zafir_F"],
            [],
            ["bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan"],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "HMG",
        [
            ["LMG_Zafir_F","MMG_01_tan_F","arifle_CTARS_blk_F"],
            [],
            ["bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan"],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "SpecialForces",
        [
            ["arifle_ARX_hex_F","arifle_CTARS_blk_F","ATC_launch_RPG32_F","arifle_CTAR_GL_blk_F","arifle_Katiba_GL_F","arifle_SDAR_F","LMG_Zafir_F","hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_Rook40_F","SMG_01_F","arifle_Katiba_F","arifle_Katiba_C_F"],
            ["ACE_optic_Arco_PIP","ACE_optic_MRCO_PIP","ACE_optic_Hamr_PIP","optic_ACO_grn","optic_Holosight","optic_aco","optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            ["bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan","acc_pointer_IR","ACE_acc_pointer_red"],
            ["muzzle_snds_L","muzzle_snds_H","muzzle_snds_acp","muzzle_snds_65_TI_blk_F","muzzle_snds_58_blk_F"],
            ["ClaymoreDirectionalMine_Remote_Mag","SatchelCharge_Remote_Mag","DemoCharge_Remote_Mag","APERSMine_Range_Mag","ATMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag","10Rnd_50BW_Mag_F"],
            [], //"10Rnd_50BW_Mag_F"
            ["ACE_Flashlight_MX991","V_HarnessO_brn","H_MilCap_ocamo","H_MilCap_ocamo","ACE_Clacker","ACE_SpottingScopeObject","ACE_SpottingScope","ACE_Altimeter","ACE_DAGR","ACE_microDAGR","ACE_NVG_Gen4","ACE_NVG_Wide","ATC_Laserdesignator_R"]
        ]   
    ],
    [
        "EXP",//obsolete
        [
            [],
            [],
            [],
            [],
            ["ClaymoreDirectionalMine_Remote_Mag","SatchelCharge_Remote_Mag","DemoCharge_Remote_Mag","ATMine_Range_Mag","APERSBoundingMine_Range_Mag","APERSTripMine_Wire_Mag","APERSMine_Range_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["ACE_M26_Clacker","ACE_DefusalKit"]
        ]   
    ],
    [
        "ENG",
        [			 
            ["ACE_VMM3"],
            [],
            [],
            [],
            [],
            [],
            ["ToolKit"]
        ]
    ],
    [
        "AT",
        [
            ["ATC_launch_RPG32_F"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAT",
        [
            ["ATC_TITAN_AT_O"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAA",
        [
            ["ATC_TITAN_AA_O"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "Sniper",
        [
            ["srifle_DMR_01_F","srifle_GM6_camo_F","srifle_DMR_05_tan_f","srifle_DMR_07_blk_F"],
            ["ACE_optic_LRPS_PIP","optic_KHS_blk","optic_DMS","optic_NVS"],
            ["bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan"],
            ["muzzle_snds_L","muzzle_snds_acp","muzzle_snds_93mmg_tan","muzzle_snds_B_snd_F"],
            [],
            [],
            ["U_O_GhillieSuit","ACE_Tripod","ACE_RangeCard"]
        ]   
    ],
    [
        "Spotter",
        [
            ["arifle_CTAR_GL_blk_F","srifle_DMR_07_blk_F"],
            ["optic_DMS","ACE_optic_Arco_PIP","ACE_optic_MRCO_PIP"],
            ["bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan"],
            ["muzzle_snds_L","muzzle_snds_acp"],							   
            ["APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag","Laserbatteries"],
            [],
            ["U_O_GhillieSuit","ACE_SpottingScopeObject","ACE_DAGR","ACE_microDAGR","ACE_Vector","ATC_Laserdesignator_R","ACE_Kestrel4500","ACE_ATragMX","ACE_RangeCard","ACE_SpottingScope"]
        ]   
    ],
	[
        "Marksman",
        [
            ["srifle_DMR_07_blk_F","srifle_DMR_07_hex_F"],
            ["optic_DMS","ACE_optic_Arco_PIP"],
            ["bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan"],
            [],
            [],
            [],
            ["ACE_RangeCard"]
        ]   
    ],
	[
        "Mortarist",
        [
            [],
            [],
            [],
            [],
            ["ACE_1Rnd_82mm_Mo_HE","ACE_1Rnd_82mm_Mo_Smoke","ACE_1Rnd_82mm_Mo_Illum","ACE_1Rnd_82mm_Mo_HE_LaserGuided"],
            [],
            ["ACE_RangeTable_82mm","ACE_Kestrel4500","ACE_DAGR"]
        ]
    ],
    [
        "DM",
        [
            ["srifle_DMR_01_F","srifle_DMR_07_blk_F"],
            ["ACE_optic_LRPS_PIP","optic_KHS_blk","optic_DMS","optic_NVS"],
            ["bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan"],
            [],
            [],
            [],
            ["ACE_Tripod","ACE_RangeCard","ACE_Kestrel4500"]
        ]   
    ]
]
