/**
* ATC_loadoutParamsA
* ["atc_unitSpecClasses", array Unit classes, false];
    [
        string Unit class,
        [
            array 0 List of allowed weapon,
            array 1 List of allowed optics,
            array 2 List of allowed pointers,
            array 3 List of allowed muzzle items,
            array 4 List of additional ammo (ex: explosives),
            array 5 List of restricted ammo,
            array 6 List of allowed items (ex: )
        ]
    ]
*/
[
    [
        "Common",
        [
            ["hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_Rook40_F","SMG_01_F","arifle_Katiba_F","arifle_Katiba_C_F"],
            ["optic_ACO_grn","optic_Holosight","optic_aco"],
            ["acc_pointer_IR","acc_flashlight"],
            [],
            ["HandGrenade","SmokeShellBlue","SmokeShellGreen","SmokeShellOrange","SmokeShellPurple","SmokeShellRed","SmokeShell","SmokeShellYellow","O_IR_Grenade","Chemlight_blue","Chemlight_green","Chemlight_red","Chemlight_yellow"],
            [],
            ["ItemMap","ItemCompass","ItemWatch","tf_fadak","FirstAidKit","NVGoggles_OPFOR","Binocular"]
        ]
    ],
    [
        "Commander",
        [
            [],
            ["optic_Arco","optic_MRCO","optic_hamr","optic_Hamr"],
            [],
            [],
            [],
            [],
            ["ItemGPS"]
        ]
    ],
    [
        "Logistic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["ItemGPS"]
        ]
    ],
    [
        "Medic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["Medikit"]
        ]
    ],
    [
        "Grenadier",
        [
            ["arifle_Katiba_GL_F"],
            [],
            [],
            [],
            ["1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"],
            [],
            []
        ]
    ],
    [
        "LMG",
        [
            ["LMG_Zafir_F"],
            ["optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp","bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan","bipod_03_F_blk","bipod_03_F_blk"],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "HMG",
        [
            ["MMG_01_hex_F"],
            [],
            [],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "SpecialForces",
        [
            ["arifle_Katiba_GL_F","arifle_SDAR_F","LMG_Zafir_F","hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_Rook40_F","SMG_01_F","arifle_Katiba_F","arifle_Katiba_C_F"],
            ["optic_Arco","optic_MRCO","optic_hamr","optic_Hamr","optic_ACO_grn","optic_Holosight","optic_aco","optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            [],
            ["muzzle_snds_L","muzzle_snds_H","muzzle_snds_acp"],
            ["DemoCharge_Remote_Mag","SatchelCharge_Remote_Mag","ATMine_Range_Mag","APERSBoundingMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["ItemGPS","Medikit","ATC_Laserdesignator_R","MineDetector"]
        ]   
    ],
    [
        "EXP",
        [
            [],
            [],
            [],
            [],
            ["DemoCharge_Remote_Mag","SatchelCharge_Remote_Mag","ATMine_Range_Mag","APERSBoundingMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["MineDetector","ToolKit"]
        ]   
    ],
    [
        "ENG",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["ToolKit"]
        ]
    ],
    [
        "AT",
        [
            ["launch_RPG32_F"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAT",
        [
            ["ATC_TITAN_AT_O"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAA",
        [
            ["ATC_TITAN_AA_O"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "Sniper",
        [
            ["srifle_DMR_01_F","srifle_GM6_F","srifle_DMR_05_hex_F"],
            ["optic_SOS","optic_LRPS","optic_KHS_blk","optic_DMS"],
            [],
            ["muzzle_snds_L","muzzle_snds_acp"],
            [],
            [],
            []
        ]   
    ],
    [
        "Spotter",
        [
            ["arifle_Katiba_GL_F"],
            ["optic_Arco","optic_MRCO","optic_hamr","optic_Hamr"],
            [],
            ["muzzle_snds_L","muzzle_snds_acp"],
            [],
            [],
            ["ItemGPS","Rangefinder","ATC_Laserdesignator_R"]
        ]   
    ],
    [
        "Marksman",
        [
            ["srifle_DMR_01_F","srifle_DMR_05_hex_F"],
            ["optic_SOS","optic_LRPS","optic_KHS_blk","optic_DMS"],
            [],
            [],
            [],
            [],
            []
        ]   
    ]
]