/**
* ATC_loadoutParamsA
* ["atc_unitSpecClasses", array Unit classes, false];
    [
        string Unit class,
        [
            array 0 List of allowed weapon,
            array 1 List of allowed optics,
            array 2 List of allowed pointers,
            array 3 List of allowed muzzle items,
            array 4 List of additional ammo (ex: explosives),
            array 5 List of restricted ammo,
            array 6 List of allowed items (ex: )
        ]
    ]
*/
[
    [
        "Common",
        [
            ["hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_P07_F","arifle_MX_F","arifle_MXC_F","SMG_02_F"],
            ["optic_Holosight","optic_aco"],
            ["acc_pointer_IR","acc_flashlight"],
            [],
            ["HandGrenade","SmokeShellBlue","SmokeShellGreen","SmokeShellOrange","SmokeShellPurple","SmokeShellRed","SmokeShellYellow","SmokeShell","B_IR_Grenade","Chemlight_blue","Chemlight_green","Chemlight_red","Chemlight_yellow"],
            [],
            ["ItemMap","ItemCompass","ItemWatch","tf_anprc152","FirstAidKit","NVGoggles","Binocular"]
        ]
    ],
    [
        "Commander",
        [
            [],
            ["optic_Arco","optic_MRCO","optic_Hamr","optic_hamr"],
            [],
            [],
            [],
            [],
            ["ItemGPS"]
        ]
    ],
    [
        "Logistic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["ItemGPS"]
        ]
    ],
    [
        "Medic",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["Medikit"]
        ]
    ],
    [
        "Grenadier",
        [
            ["arifle_MX_GL_F"],
            [],
            [],
            [],
            ["1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell"],
            [],
            []
        ]
    ],
    [
        "LMG",
        [
            ["LMG_Mk200_F"],
            ["optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp","bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan","bipod_03_F_blk","bipod_03_F_blk"],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "HMG",
        [
            ["MMG_02_sand_F"],
            [],
            [],
            [],
            [],
            [],
            []
        ]
    ],
    [
        "SpecialForces",
        [
            ["arifle_SDAR_F","LMG_Mk200_F","hgun_Pistol_heavy_01_F","hgun_ACPC2_F","hgun_P07_F","arifle_MX_F","arifle_MXC_F","SMG_02_F"],
            ["optic_Arco","optic_MRCO","optic_Hamr","optic_hamr","optic_Holosight","optic_aco","optic_Holosight_smg","optic_Aco_smg","optic_ACO_grn_smg"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp","bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan","bipod_03_F_blk","bipod_03_F_blk"],
            ["muzzle_snds_L","muzzle_snds_H","muzzle_snds_acp"],
            ["Laserbatteries","DemoCharge_Remote_Mag","SatchelCharge_Remote_Mag","ATMine_Range_Mag","APERSBoundingMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["ItemGPS","Medikit","ATC_Laserdesignator_B","MineDetector"]
        ]   
    ],
    [
        "EXP",
        [
            [],
            [],
            [],
            [],
            ["DemoCharge_Remote_Mag","SatchelCharge_Remote_Mag","ATMine_Range_Mag","APERSBoundingMine_Range_Mag","APERSTripMine_Wire_Mag","ClaymoreDirectionalMine_Remote_Mag"],
            [],
            ["MineDetector","ToolKit"]
        ]   
    ],
    [
        "ENG",
        [
            [],
            [],
            [],
            [],
            [],
            [],
            ["ToolKit"]
        ]
    ],
    [
        "AT",
        [
            ["ATC_NLAW"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAT",
        [
            ["ATC_TITAN_AT_B"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "HAA",
        [
            ["ATC_TITAN_AA_B"],
            [],
            [],
            [],
            [],
            [],
            []
        ]   
    ],
    [
        "Sniper",
        [
            ["arifle_MXM_F","srifle_LRR_F","srifle_DMR_02_sniper_F"],
            ["optic_SOS","optic_LRPS","optic_AMS","optic_DMS","optic_Arco","optic_MRCO","optic_hamr","optic_Hamr","optic_hamr"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp","bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan","bipod_03_F_blk","bipod_03_F_blk"],
            ["muzzle_snds_L","muzzle_snds_acp"],
            [],
            [],
            ["ItemGPS"]
        ]   
    ],
    [
        "Spotter",
        [
            ["arifle_MX_GL_F"],
            ["optic_Arco","optic_MRCO","optic_hamr","optic_Hamr","optic_hamr"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp","bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan","bipod_03_F_blk","bipod_03_F_blk"],
            ["muzzle_snds_L","muzzle_snds_acp"],
            ["Laserbatteries"],
            [],
            ["ItemGPS","Rangefinder","ATC_Laserdesignator_B"]
        ]   
    ],
    [
        "Marksman",
        [
            ["arifle_MXM_F","srifle_DMR_02_sniper_F"],
            ["optic_SOS","optic_LRPS","optic_AMS","optic_DMS","optic_Arco","optic_MRCO","optic_hamr","optic_Hamr","optic_Nightstalker","optic_hamr"],
            ["bipod_01_F_snd","bipod_01_F_blk","bipod_01_F_mtp","bipod_02_F_blk","bipod_02_F_hex","bipod_02_F_tan","bipod_03_F_blk","bipod_03_F_blk"],
            [],
            [],
            [],
            []
        ]   
    ]
]